### ISSUE TITLE
improve scramble algorithm

### ISSUE THREAD

**Issue by NicolasToussaint** [mzhang/cleanTimer#1]
Thanks for the app, I love it :-)

I can propose a small idea for improvement.

The scramble code often is not ideal as move will simply cancel the previous one like `R2 R2`
And also, print a reminder of what the letters refer to, I keep forgetting :-)

**Comment by mzhang** [comment]
Fixed in #2 . Thank you to @BoostCookie! Please look forward to release v1.1 :)
