### ISSUE TITLE
Use correct duration time format

### ISSUE THREAD

**Issue by BoostCookie** [mzhang/cleanTimer#3]
A time of 1 minute and 32.448 seconds is represented as
01:32:448
right now. This is wrong. The number of seconds is just a decimal number that should have a decimal point to separate the whole part from the fractional part. It should be
01:32.448
instead. Or maybe even use the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) standard:
PT01M32.448S

**Comment by mzhang** [comment]
Closed on #4 . Thank you again to @BoostCookie for the issue + pr! 

Will likely repackage + release when issue #5 is resolved.
