### ISSUE TITLE
Why fullscreen?

### ISSUE THREAD

**Issue by BoostCookie** [mzhang/cleanTimer#5]
I personally think fullscreen for this app is unnecessary and annoying. When viewing the stats it's quite difficult to swipe up to make the navigation bar appear and then click fast enough to go back to the main screen before the bar disappears again.

What does the maintainer think?

**Comment by mzhang** [comment]
I agree with you. I must have had it before to make it feel more immersive with gestures but I think it does mess up people who use the navbar. Would you like to make a pull request or would you like me to rip out the immersive mode flags instead?

**Comment by mzhang** [comment]
Fixed with commit 278a18c and packaged for release. Thanks for the feedback 👍

**Comment by fAntel** [comment]
@mzhang it seems there is no 1.2 version in F-Droid.
